spring:
  datasource:
    url: "jdbc:mysql://${PRODUCT_DB_HOST:localhost}:${PRODUCT_DB_PORT:3318}/${PRODUCT_DB_DATABASE:product}"
    username: ${PRODUCT_DB_USER:root}
    password: ${PRODUCT_DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: ${SQL_INIT_MODE:never}

  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
      ejb:
        naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy