spring:
  application:
    name: service-product

server:
  servlet:
    context-path: /product
  port: 8663

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost