spring:
  application:
    name: service-product
  config:
    import:
      - "optional:classpath:/config/cloud.yml"
      - "optional:classpath:/config/database.yml"

  profiles:
    active: ${PROFILE:dev}