spring:
  config:
    activate:
      on-profile: prod

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    enabled: false